var adj=["peer-to-peer",    	"social media",	"distributed",	"industry strength",	"virtual",	"autonomous",	"adaptive",	"cross compatible",	"provably fair",	"multi-agent",	"randomly generated",	"voice activated",	"backwards compatible",	"cloud based",	"open source",	"extendible",	"resource sensitive",	"environmentally friendly",	"cryptographic",	"anonymous",	"user friendly",	"big data",	"parallelized",	"high-speed"];


var topic=["parking",    	  "grading",	  "research",	  "college dating",	  "party",	  "student loan",	  "textbook exchange",	  "frat",	  "sorority",	  "university organization",	  "time management",	  "carpooling",	  "campus health",	  "volunteering",	  "outreach",      "finals",      "professor rating",    "cafeteria",     "crime tracking",  "mental health", "university health services", 	  "tutoring",	  "graduation",	  "admissions",	  "judicial board",	  "drinking",	  "schedule"];


var tech=["Rails",    	  "Python",	  "C++",	  "JavaScript",	  "Node.js",	  "C",	  "Assembly",	  "Java",	  "Matlab",	  "R",	  "PHP",	  "Lisp",	  "Perl",	  "Visual Basic",	  "Processing",	  "OpenSSL",	  "Django",	  "no libraries",	  "jQuery",	  "Hadoop",	  "MySQL",	  "lots of templates",	  "delayed evaluation",	  "less than 512 KB of memory",	  "map-reduce",	  "Google Maps",     "homomorphic encryption", "GPGPU",     "hill climbing",  "quicksort",   "genetic algorithms", "fast fourier transforms", "O(n) worst case run time", "garbage collection",  "facial recognition",   "a Raspberry Pi",  	  "Amazon EC2",	  "Markov chains",	  "alpha beta pruning",	  "red/black trees",	  "Djikstra's algorithm",	  "SAT solvers",	  "eliptic curve cryptography",	  "OpenCV",	  "Weka",	  "metasploit"];

var noun=["firewall",    	  "Android app",	  "iPhone app",	  "framework",	  "library",	  "email client",	  "spam filter",	  "microblogging service",	  "language",	  "videogame",	  "experiment",	  "database",	  "package",	  "toolkit",	  "kernel extension",	  "browser plugin",	  "website",	  "program",	  "operating system",	  "API",	  "service",	  "payment processor",	  "news aggregator",	  "chat client",	  "firmware",	  "DLL",	  "trading bot",	  "filesystem",	  "version control system",	  "algorithm"];
